export async function onRequestPost({ request, env }) {
    try {
        const { message, systemPrompt, history, userMode, model: requestedModel } = await request.json();

        const apiKey = env.GEMINI_API_KEY;
        if (!apiKey) {
            return new Response(JSON.stringify({ error: "Gemini API key is not configured as a secret." }), {
                status: 500,
                headers: { "Content-Type": "application/json" },
            });
        }

        // Default to gemini-1.5-flash if not specified
        const modelId = requestedModel || "gemini-1.5-flash";
        const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${apiKey}`;

        // Format history for Gemini API
        const formattedHistory = (history || []).map(m => ({
            role: m.role === "user" ? "user" : "model",
            parts: m.parts || [{ text: m.text }]
        }));

        const payload = {
            contents: [...formattedHistory, { role: "user", parts: [{ text: message }] }],
            generationConfig: {
                maxOutputTokens: userMode === "PREMIUM" ? 500 : 200,
                temperature: 0.8,
            }
        };

        if (systemPrompt) {
            payload.systemInstruction = {
                parts: [{ text: systemPrompt }]
            };
        }

        const response = await fetch(API_URL, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
        });

        const data = await response.json();

        if (!response.ok) {
            return new Response(JSON.stringify({
                error: data.error?.message || "Gemini API calling failed",
                details: data.error
            }), {
                status: response.status,
                headers: { "Content-Type": "application/json" },
            });
        }

        // Handle both text responses and potential inlineData (images)
        const candidate = data.candidates?.[0];
        if (!candidate) {
            return new Response(JSON.stringify({ error: "No response generated by AI." }), {
                status: 500,
                headers: { "Content-Type": "application/json" },
            });
        }

        const responseParts = candidate.content?.parts || [];
        let responseText = "";
        let inlineData = null;

        for (const part of responseParts) {
            if (part.text) responseText += part.text;
            if (part.inlineData) inlineData = part.inlineData;
        }

        return new Response(JSON.stringify({
            text: responseText || "No text response.",
            inlineData: inlineData
        }), {
            headers: { "Content-Type": "application/json" },
        });

    } catch (error) {
        return new Response(JSON.stringify({ error: error.message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
        });
    }
}
