
import React, { useEffect } from 'react';
import { ArrowLeft, HelpCircle, Mail } from 'lucide-react';

interface PageProps {
  onBack: () => void;
}

const FAQPage: React.FC<PageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const faqs = [
    {
      q: "What is CallHub AI?",
      a: "CallHub AI is an online platform that lets you connect with virtual AI companions. You can chat via text or have realistic voice calls with AI characters designed for entertainment, emotional comfort, and friendship."
    },
    {
      q: "Is this a real dating service?",
      a: "No. CallHub AI provides interactions with fictional, digitally generated characters. It is not a platform for social networking or matchmaking."
    },
    {
      q: "How do the AI Companion characters work?",
      a: "Our characters use advanced artificial intelligence technology to understand your messages and respond with personality, emotion, and memory, simulating a natural conversation."
    },
    {
      q: "What are Conversation Styles?",
      a: "Conversation Styles (like Playful, Warm, or Gentle) determine the 'vibe' of your companion. When you create a character in a specific style, their personality is set to that tone to give you a consistent experience."
    },
    {
      q: "Is my chat private?",
      a: "Yes. Your conversations are private and are not shared publicly. We prioritize user discretion and data security."
    },
    {
      q: "Can I upload my own photo for my character?",
      a: "Yes! When creating a custom companion, you can either upload your own photo or use our AI to generate a unique look for them."
    },
    {
      q: "Is CallHub AI safe?",
      a: "We strive to create a safe, judgment-free environment. We have guidelines in place to prevent misuse and ensure interactions remain respectful."
    },
    {
      q: "What age do I need to be to use this?",
      a: "You must be 18 years or older to access or use the CallHub AI platform."
    },
    {
      q: "Do I speak to real humans on calls?",
      a: "No. All voice calls are generated by AI voice technology. You are interacting with a virtual character, not a human operator."
    },
    {
      q: "How do subscriptions work?",
      a: "If the platform offers premium features, payments are handled securely through RBI-compliant payment gateways. We do not store your payment card details directly."
    },
    {
      q: "Can I delete my data or profile?",
      a: "Absolutely. You have full control. You can request to delete specific characters or your entire account at any time via the settings or by contacting support."
    },
    {
      q: "Who do I contact for support?",
      a: "If you need help or have questions, please email our support team at support@callhub.in."
    }
  ];

  return (
    <div className="min-h-screen w-full bg-[#FDF2F8] font-sans text-[#5e3a58]">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-[#FDF2F8]/90 backdrop-blur-md border-b border-[#B28DFF]/20 px-6 py-4 flex items-center gap-4">
        <button
          onClick={onBack}
          className="p-2 -ml-2 rounded-full hover:bg-black/5 text-[#5e3a58] transition-colors"
        >
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-serif-display font-bold text-[#4A2040]">FAQ</h1>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-8 space-y-8">

        <div className="text-center space-y-2 mb-8">
          <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center mx-auto shadow-sm text-[#B28DFF]">
            <HelpCircle size={24} />
          </div>
          <h2 className="text-2xl font-serif-display text-[#4A2040]">Frequently Asked Questions</h2>
          <p className="text-sm opacity-80">Common questions about the CallHub experience.</p>
        </div>

        <div className="space-y-6">
          {faqs.map((item, index) => (
            <div key={index} className="bg-white/40 border border-white/60 rounded-2xl p-5 shadow-sm hover:bg-white/60 transition-colors">
              <h3 className="text-base font-bold text-[#4A2040] mb-2">{item.q}</h3>
              <p className="text-sm leading-relaxed opacity-90 text-[#5e3a58]">{item.a}</p>
            </div>
          ))}
        </div>

        <section className="space-y-4 bg-[#FFF0F5] p-6 rounded-2xl border border-[#B28DFF]/20 text-center mt-8">
          <h3 className="text-lg font-bold text-[#4A2040]">Still have questions?</h3>
          <p className="opacity-90 mb-4 text-sm">
            We are here to help. Reach out to us anytime.
          </p>
          <a href="mailto:support@callhub.in" className="inline-flex items-center gap-2 text-[#B28DFF] font-medium hover:underline bg-white px-4 py-2 rounded-full shadow-sm">
            <Mail size={16} /> support@callhub.in
          </a>
        </section>

      </div>

      {/* Footer */}
      <footer className="py-8 px-6 text-center border-t border-[#B28DFF]/10 bg-[#FFF0F5]">
        <p className="text-[#5e3a58]/60 text-xs font-medium leading-loose">
          © 2025 CallHub • All Rights Reserved • 18+ Only<br />
          Designed for safe, private emotional AI interactions
        </p>
      </footer>
    </div>
  );
};

export default FAQPage;