
import React, { useEffect } from 'react';
import { ArrowLeft, Shield } from 'lucide-react';

interface PageProps {
  onBack: () => void;
}

const PrivacyPage: React.FC<PageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen w-full bg-[#FDF2F8] font-sans text-[#5e3a58]">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-[#FDF2F8]/90 backdrop-blur-md border-b border-[#B28DFF]/20 px-6 py-4 flex items-center gap-4">
        <button
          onClick={onBack}
          className="p-2 -ml-2 rounded-full hover:bg-black/5 text-[#5e3a58] transition-colors"
        >
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-serif-display font-bold text-[#4A2040]">Privacy Policy</h1>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-8 space-y-8">

        <p className="leading-relaxed opacity-90 text-sm italic">
          At CallHub, your privacy is our priority. This policy outlines how we handle data for our AI-based conversational platform designed for entertainment and emotional well-being.
        </p>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">1. AI Interaction Disclaimer</h3>
          <p className="opacity-90">
            All responses on CallHub are generated by Artificial Intelligence. There is <strong>no real human interaction</strong> involved in the chat or calling features. Conversations are simulated for entertainment purposes.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">2. Information We Collect</h3>
          <ul className="space-y-2 list-disc pl-5 opacity-90">
            <li><strong>Account Data:</strong> Nickname and preferences provided by you.</li>
            <li><strong>Chat Logs:</strong> Simulated interactions stored locally or on secure servers to maintain context.</li>
            <li><strong>Usage Metadata:</strong> Device type and basic analytics to improve platform performance.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">3. Data Usage & Safety</h3>
          <p className="opacity-90">
            We use your data strictly to personalize your AI experience. We <strong>do not sell</strong> your personal information to third parties. All data is processed to enhance the "Virtual Companion" experience.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">4. Data Deletion</h3>
          <p className="opacity-90">
            You can request the deletion of your data at any time by contacting our support team. Locally stored chats can be cleared directly from the app settings.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">5. Age Requirement</h3>
          <p className="opacity-90">
            CallHub is strictly for users aged 18 and older. We do not knowingly collect information from individuals under 18.
          </p>
        </section>

        <section className="space-y-3 bg-white/50 p-6 rounded-2xl border border-white/60">
          <h3 className="text-lg font-bold text-[#4A2040]">Contact Support</h3>
          <p className="opacity-90 mb-2">For any privacy-related queries or data deletion requests, email us at:</p>
          <a href="mailto:support@callhub.in" className="text-[#B28DFF] font-medium hover:underline block">
            support@callhub.in
          </a>
        </section>

      </div>

      {/* Footer */}
      <footer className="py-8 px-6 text-center border-t border-[#B28DFF]/10 bg-[#FFF0F5]">
        <p className="text-[#5e3a58]/60 text-xs font-medium leading-loose">
          © 2026 CallHub AI • All Rights Reserved • 18+ Only<br />
          Entertainment & Emotional Well-being Platform
        </p>
      </footer>
    </div>
  );
};

export default PrivacyPage;