
import React, { useEffect } from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

interface PageProps {
  onBack: () => void;
}

const TermsPage: React.FC<PageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen w-full bg-[#FDF2F8] font-sans text-[#5e3a58]">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-[#FDF2F8]/90 backdrop-blur-md border-b border-[#B28DFF]/20 px-6 py-4 flex items-center gap-4">
        <button
          onClick={onBack}
          className="p-2 -ml-2 rounded-full hover:bg-black/5 text-[#5e3a58] transition-colors"
        >
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-serif-display font-bold text-[#4A2040]">Terms of Service</h1>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-8 space-y-8">

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">1. Platform Purpose</h3>
          <p className="opacity-90">
            CallHub AI is a platform intended strictly for conversational entertainment. All characters, messages, and responses are generated by artificial intelligence and are fictional. The service is designed for entertainment and creative expression only.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">2. Eligibility</h3>
          <p className="opacity-90">
            You must be at least 18 years of age to use this platform. By continuing, you represent that you meet this age requirement. We reserve the right to terminate access if we believe a user is under the legal age.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">3. AI-Only Nature</h3>
          <p className="opacity-90">
            All interactions on this platform are 100% AI-generated. There are no real humans involved in the generation of chat or voice content. The interactions do not represent real-world relationships, dating services, or professional advice.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">4. User Responsibility</h3>
          <p className="opacity-90">
            Users are responsible for their own interactions and conduct on the platform. Any attempt to abuse, disrupt, or use the service for illegal activities is strictly prohibited.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">5. Payments & Digital Credits</h3>
          <div className="bg-[#B28DFF]/5 p-4 rounded-xl border border-[#B28DFF]/10 space-y-4">
            <p className="text-sm opacity-90 leading-relaxed">
              CallHub offers digital credits for accessing AI-powered conversational features. Credits are virtual, non-transferable, and have no real-world monetary value.
            </p>
            <ul className="space-y-2 text-sm list-disc pl-5 opacity-90">
              <li>Credits (Hearts) are added <strong>instantly</strong> after successful payment confirmation.</li>
              <li>Due to the digital and consumable nature of AI-generated services, <strong>refunds are not provided</strong> once credits are used.</li>
              <li>Duplicate or failed transactions will be reviewed and refunded within <strong>5-7 business days</strong>.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">6. Limitation of Liability</h3>
          <p className="opacity-90">
            CallHub AI is provided on an "as-is" and "as-available" basis. We are not liable for any emotional outcomes, perceived relationships, or reliance on information provided by the AI. We do not guarantee the accuracy or appropriateness of AI-generated content.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">7. Service Availability</h3>
          <p className="opacity-90">
            While we strive for consistent uptime, we do not guarantee that the service will be available at all times without interruption. We reserve the right to modify, suspend, or terminate the service at our sole discretion.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">8. Governing Law</h3>
          <p className="opacity-90">
            These terms are governed by the laws of India. Any disputes arising from the use of this service shall be subject to the exclusive jurisdiction of the courts in India.
          </p>
        </section>

        <section className="space-y-3 bg-white/50 p-6 rounded-2xl border border-white/60">
          <h3 className="text-lg font-bold text-[#4A2040]">Contact Us</h3>
          <p className="opacity-90 mb-2">For any legal or terms-related questions, please email:</p>
          <a href="mailto:support@callhub.in" className="text-[#B28DFF] font-medium hover:underline block">
            support@callhub.in
          </a>
        </section>

      </div>

      {/* Footer */}
      <footer className="py-8 px-6 text-center border-t border-[#B28DFF]/10 bg-[#FFF0F5]">
        <p className="text-[#5e3a58]/60 text-xs font-medium leading-loose">
          © 2026 CallHub AI • All Rights Reserved • 18+ Only<br />
          Entertainment & Well-being Platform
        </p>
      </footer>
    </div>
  );
};

export default TermsPage;