
export const loadRazorpay = () => {
    return new Promise((resolve) => {
        const script = document.createElement('script');
        script.src = 'https://checkout.razorpay.com/v1/checkout.js';
        script.onload = () => resolve(true);
        script.onerror = () => resolve(false);
        document.body.appendChild(script);
    });
};

export const initiatePayment = async (options: {
    amount: number;
    currency: string;
    name: string;
    description: string;
    userEmail: string;
    userPhone?: string;
    onSuccess: (response: any) => void;
    onFailure: (error: any) => void;
}) => {
    const isLoaded = await loadRazorpay();

    if (!isLoaded) {
        alert('Razorpay SDK failed to load. Are you online?');
        return;
    }

    // Note: In production, 'order_id' must be generated by your BACKEND via Razorpay API for security.
    const rzpKey = import.meta.env.VITE_RAZORPAY_KEY_ID;
    if (!rzpKey) {
        alert("Razorpay Key ID missing! Please add VITE_RAZORPAY_KEY_ID to your .env.local file.");
        return;
    }

    const razorpayOptions = {
        key: rzpKey,
        amount: options.amount * 100,
        currency: options.currency,
        name: "CallHub AI",
        description: options.description,
        image: "https://your-logo-url.com/logo.png",
        handler: function (response: any) {
            // This is the SUCCESS callback
            // response.razorpay_payment_id
            // response.razorpay_order_id
            // response.razorpay_signature
            options.onSuccess(response);
        },
        prefill: {
            name: options.name,
            email: options.userEmail,
            contact: options.userPhone || ""
        },
        notes: {
            address: "CallHub AI Headquarters"
        },
        theme: {
            color: "#FF9ACB" // Matching your Pink-UI
        }
    };

    const rzp = new (window as any).Razorpay(razorpayOptions);
    rzp.on('payment.failed', function (response: any) {
        options.onFailure(response.error);
    });
    rzp.open();
};
